# Generated by Django 3.0.8 on 2020-08-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=12)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=10)),
                ('internal', models.IntegerField()),
                ('sub1_marks', models.IntegerField()),
                ('sub2_marks', models.IntegerField()),
                ('sub3_marks', models.IntegerField()),
                ('sub4_marks', models.IntegerField()),
                ('sub5_marks', models.IntegerField()),
                ('sub6_marks', models.IntegerField()),
                ('sub7_marks', models.IntegerField()),
                ('sub8_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub1', models.CharField(max_length=50)),
                ('sub2', models.CharField(max_length=50)),
                ('sub3', models.CharField(max_length=50)),
                ('sub4', models.CharField(max_length=50)),
                ('sub5', models.CharField(max_length=50)),
                ('sub6', models.CharField(max_length=50)),
                ('sub7', models.CharField(max_length=50)),
                ('sub8', models.CharField(max_length=50)),
            ],
        ),
    ]
