# Generated by Django 3.0.8 on 2020-08-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
