# Generated by Django 3.0.8 on 2020-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semister',
            fields=[
                ('sem_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('usn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
