# Generated by Django 3.0.8 on 2020-08-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_branch_semister_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=10)),
                ('Internal', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='toppersspic')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
