# Generated by Django 3.0.8 on 2020-08-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_topper'),
    ]

    operations = [
        migrations.CreateModel(
            name='CseTopper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=10)),
                ('Internal', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='toppersspic')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EceTopper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=10)),
                ('Internal', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='toppersspic')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IseTopper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=10)),
                ('Internal', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='toppersspic')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MechTopper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.CharField(max_length=10)),
                ('Internal', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='toppersspic')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Topper',
            new_name='CivilTopper',
        ),
    ]
